/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GeneratorOptions } from './types';

export function generatePythonScript(options: GeneratorOptions): string {
  const hashFunc = options.hashAlgorithm === 'md5' ? 'hashlib.md5()' : 'hashlib.sha256()';
  const blockBytes = options.blockSize;
  const hashLengthDesc = options.hashAlgorithm === 'md5' ? '128-bit (32 character hex) digest' : '256-bit (64 character hex) digest';
  
  // Create default filter directories array for display in code
  const parsedExcludeDirs = options.excludeDirs
    .split(',')
    .map(d => d.trim())
    .filter(Boolean);
  const excludePythonList = parsedExcludeDirs.length > 0 
    ? `[${parsedExcludeDirs.map(d => `'${d}'`).join(', ')}]` 
    : '[]';

  const script = `#!/usr/bin/env python3
"""
Duplicate File Finder & Storage Analyzer
========================================
An expert-grade systems engineering portfolio project.
Designed and implemented strictly using Python's standard library to inspect 
directories recursively, compute distinct content hash fingerprints, and 
identify redundant file storage patterns to calculate recoverable disk space.

Computer Science Concepts Illustrated:
-------------------------------------
1. Hash Map / HashMap (Python Dictionary) lookup optimization:
   - A direct collision-resistant content mapping strategy.
   - Standard O(1) average lookup and insertion time complexity.
   - Resolves O(N^2) naive pairwise comparisons down to highly performant O(N) operations.

2. Content Hashing over Metadata:
   - Hashing file actual bytes ensures file integrity assessments.
   - Mitigates false outcomes caused by modified file names, extensions, or metadata.
   - Implemented using memory-efficient chunk-by-chunk stream buffers.

Author: CS Portfolio Project Candidate
License: MIT
"""

import os
import hashlib
import sys
from typing import Dict, List, Tuple


def calculate_file_hash(file_path: str, block_size: int = ${blockBytes}) -> str:
    """
    Computes a cryptographic fingerprint of a file's actual content.
    
    Why Hashing Content Is More Accurate Than Relying on Names or Extensions:
    ------------------------------------------------------------------------
    Filenames are purely descriptive metadata pointers managed by the OS directory
    index. They are highly mutable, non-unique, and trivial to alter.
    
    Two distinct files may share the name "invoice.pdf" but contain completely 
    different text. Conversely, a file named "photo_copy(1).jpg" shares identical 
    pixel content with "photo.jpg".
    
    By streaming the raw bytes of a file through a hash function (like SHA-256 or MD5), 
    we reduce the entire contents (regardless of size) to a singular, fixed-length unique 
    fingerprint (the digest). If even a single bit changes in the source file, the 
    avalanche effect in cryptographic hashes produces an entirely different digest.
    
    Memory Efficiency:
    ------------------
    We load the file in small, fixed-size chunks (e.g., ${blockBytes} bytes) instead of 
    reading the whole file into RAM. This ensures that large files (even gigabyte-scale video 
    files) can be hashed without causing an Out-Of-Memory (OOM) crash on the target host.
    """
    hasher = ${hashFunc}
    
    try:
        # Open in binary mode ('rb') to read raw byte streams, avoiding encoding translations
        with open(file_path, 'rb') as f:
            while True:
                chunk = f.read(block_size)
                if not chunk:
                    break
                hasher.update(chunk)
        return hasher.hexdigest()
    except (PermissionError, FileNotFoundError, OSError) as e:
        # Gracefully handle file locked states or specialized system sockets/pipes
        return ""


def scan_directory(
    root_dir: str, 
    min_size_bytes: int = ${options.minSizeKb * 1024},
    exclude_dirs: List[str] = ${excludePythonList},
    exclude_hidden: bool = ${options.excludeHidden ? 'True' : 'False'}
) -> Tuple[Dict[str, List[str]], int, int]:
    """
    Recursively scans the directory tree using an OS level walkthrough.
    
    Computer Science Theory - Designing the Storage Lookup Engine:
    --------------------------------------------------------------
    We use a Hash Map (implemented as Python's standard 'dict') to collect files.
    - Key (String): The content hash generated by calculate_file_hash().
    - Value (List of Strings): Full system paths where this exact content resides.
    
    Time Complexity Analysis:
    -------------------------
    - If comparing each file to every other file (Pairwise verification), 
      the number of comparisons is N * (N - 1) / 2, resulting in O(N^2) complexity.
      For 10,000 files, this takes ~50,000,000 comparison loops.
    - Using a Hash Map, we scan each file exactly once, compute its hash, and
      immediately look it up or insert it in the map. The insertion/lookup complexity 
      for Python dict is O(1) on average. Thus, the total scan complexity is 
      strictly O(N * (F / B)) where F is file size and B is block size, yielding a total 
      linear runtime of O(N). For 10,000 files, this takes exactly 10,000 steps!
    """
    hash_map: Dict[str, List[str]] = {}
    total_files_scanned = 0
    total_evaluated_bytes = 0

    print(f"\\n[+] Initiating deep directory walk of: {root_dir}")
    print("[+] Using ${options.hashAlgorithm.toUpperCase()} hash algorithm with standard O(1) Hash Map insertions...")

    # os.walk yields a 3-tuple: (current_dir_path, subdirectories, filenames)
    for dirpath, dirnames, filenames in os.walk(root_dir):
        # Pruning excluded directories in-place to optimize traversal and stop descending
        if exclude_dirs:
            dirnames[:] = [d for d in dirnames if d not in exclude_dirs]
            
        if exclude_hidden:
            # Exclude hidden directories (names starting with dot)
            dirnames[:] = [d for d in dirnames if not d.startswith('.')]
            # Exclude hidden files
            filenames = [f for f in filenames if not f.startswith('.')]

        for filename in filenames:
            full_path = os.path.join(dirpath, filename)
            
            try:
                # Follow symlinks cautiously or skip them to avoid cyclical loops
                if os.path.islink(full_path):
                    continue
                    
                file_size = os.path.getsize(full_path)
                
                # Check minimum file size criteria
                if file_size < min_size_bytes:
                    continue
                    
                total_files_scanned += 1
                total_evaluated_bytes += file_size
                
                # Progress logging for real-time visual assessment
                print(f"    Scanning: {full_path[:60]}...", end="\\r")
                
                # Calculatecontent hash (the map key)
                file_hash = calculate_file_hash(full_path)
                if not file_hash:
                    continue
                
                # O(1) Average Lookup & Append
                if file_hash in hash_map:
                    hash_map[file_hash].append(full_path)
                else:
                    hash_map[file_hash] = [full_path]
                    
            except OSError:
                continue

    # Clean the tailing space of the carriage return progress bar
    print(" " * 80, end="\\r")
    return hash_map, total_files_scanned, total_evaluated_bytes


def evaluate_redundancies(hash_map: Dict[str, List[str]]) -> Tuple[Dict[str, List[str]], int]:
    """
    Processes the storage map bucket lists to filter out non-duplicate hashes.
    
    - Duplicate check condition: len(paths) > 1.
    - Computes overall space wasted by deducting the size of the original "source" file
      from each redundant bucket grouping.
    """
    duplicates: Dict[str, List[str]] = {}
    potential_space_wasted = 0

    for file_hash, paths in hash_map.items():
        if len(paths) > 1:
            duplicates[file_hash] = paths
            
            try:
                # Size of single original file in bytes
                original_file_size = os.path.getsize(paths[0])
                # Redundant count = total items in group - 1 original
                redundant_files_count = len(paths) - 1
                potential_space_wasted += original_file_size * redundant_files_count
            except OSError:
                continue

    return duplicates, potential_space_wasted


def format_size(size_bytes: float) -> str:
    """Utility formatter for system storage metrics."""
    if size_bytes < 1024:
        return f"{size_bytes:.2f} Bytes"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.2f} KB"
    else:
        return f"{size_bytes / (1024 * 1024):.2f} MB"


def print_report(
    duplicates: Dict[str, List[str]], 
    total_files: int, 
    total_bytes: int, 
    wasted_bytes: int
) -> None:
    """
    Prints a stunning, developer-grade terminal overview and diagnostic summary.
    """
    print("=" * 70)
    print("         DUPLICATE FILE SCANNER - STORAGE breakdown REPORT")
    print("=" * 70)
    print(f"📂  Total Directories & Subdirectories Explored")
    print(f"📊  Total Files Scanned      : {total_files:,}")
    print(f"💾  Total Disk Volume Checked: {format_size(total_bytes)}")
    print(f"💡  Potential Space Wasted   : {format_size(wasted_bytes)}")
    print(f"📋  Unique Digital Duplicates: {len(duplicates)}")
    print("-" * 70)

    if not duplicates:
        print("\\n✨ Great news! No duplicate file contents were found. Storage and index integrity are optimal.")
        print("=" * 70)
        return

    # Sort duplicates descending by wasting capacity (largest size first)
    sorted_dupes = []
    for f_hash, paths in duplicates.items():
        try:
            sz = os.path.getsize(paths[0])
            total_group_waste = sz * (len(paths) - 1)
            sorted_dupes.append((total_group_waste, sz, f_hash, paths))
        except OSError:
            continue
            
    sorted_dupes.sort(key=lambda x: x[0], reverse=True)

    print("\\n[🔥] DETAILED BREAKDOWN OF REDUNDANT BUCKETS (Sorted by Wasted Space):")
    for group_waste, single_size, f_hash, paths in sorted_dupes:
        print(f"\\nHash Fingerprint: {f_hash}")
        print(f"  Single File Size: {format_size(single_size)} | Redundant Waste: {format_size(group_waste)}")
        print(f"  Exact Paths Grouping ({len(paths)} copies):")
        for i, path in enumerate(paths):
            role_tag = "[Original Copy]" if i == 0 else "[Duplicate Content]"
            print(f"   -> {role_tag} {path}")
            
    print("=" * 70)
    print("🔑 RECRUITER SPECS: The HashMap lookup strategy achieved real-time O(N) execution.")
    print("=" * 70)


def main() -> None:
    """Runs the CLI controller loop."""
    print("======================================================================")
    print("             Duplicate File Finder & Storage Analyzer CLI             ")
    print("======================================================================")

    # Validate interactive argument or grab from CLI prompt
    if len(sys.argv) > 1:
        target_dir = sys.argv[1]
    else:
        target_dir = input("Enter standard folder directory to scan (e.g., . or ./data): ").strip()

    if not target_dir:
        print("[-] Error: Path argument cannot be empty.")
        sys.exit(1)

    # Perform filesystem path verification
    if not os.path.exists(target_dir):
        print(f"[-] Error: Target path '{target_dir}' does not exist on this machine.")
        sys.exit(1)

    if not os.path.isdir(target_dir):
        print(f"[-] Error: Target path '{target_dir}' is a file, not a directory.")
        sys.exit(1)

    try:
        # Step 1: Walkway scanning phase
        all_files_map, files_scanned, evaluated_bytes = scan_directory(target_dir)
        
        # Step 2: Evaluation calculations
        dupe_map, wasted_bytes = evaluate_redundancies(all_files_map)
        
        # Step 3: Print structured visual metrics
        print_report(dupe_map, files_scanned, evaluated_bytes, wasted_bytes)

    except KeyboardInterrupt:
        print("\\n[-] Scan aborted by the terminal session operator.")
        sys.exit(1)


if __name__ == '__main__':
    main()
`;
  return script;
}
